### ISSUE TITLE
Recording is of a screen with "Missing Authentication Token"

### ISSUE THREAD

**Issue by mrgrue** [aws-samples/amazon-chime-sdk-recording-demo#22]
After following all the instructions, the recording was not of the full web page (as described in the instructions). Instead, the movie was of a recording of a web console. I'm attaching a screenshot:

![recorded-movie-screenshot](https://user-images.githubusercontent.com/3343244/84841486-aea82d80-afff-11ea-92c2-279a38b2aaec.png)

Where do I get the token it's referring to, and where do I put it?

**Comment by anuranduttaroy** [comment]
Can you give us the exact steps to reproduce the issue?

**Comment by davidilieberman** [comment]
I have had the same experience, following the README recipe carefully, multiple times. ECS log setting up the firefox recording agent is attached. During the meeting, the users get no active indication that the recording agent has joined the meeting, and the resulting file is identical to the screenshot provided by @mrgrue . The only indication of an issue in the log is at line 37 in the attached file, which seems to be calling out a missing dependency.

[log-events-viewer-result.log](https://github.com/aws-samples/amazon-chime-sdk-recording-demo/files/4833853/log-events-viewer-result.log)

**Comment by anuranduttaroy** [comment]
Recording seems to be working fine since the there was a video.

The issue seems to be with the meeting URL you are passing to the recording function.

As written in this section of the readme: [Start an Amazon Chime SDK meeting with our serverless demo and join with multiple participants](https://github.com/aws-samples/amazon-chime-sdk-recording-demo#start-an-amazon-chime-sdk-meeting-with-our-serverless-demo-and-join-with-multiple-participants), the format of the Meeting URL should be something like this 

`https://abcdefghij.execute-api.us-east-1.amazonaws.com/Prod/v2?m=<meeting-id>`

The "Missing Authentication Token" error is shown when the meeting URL is incorrect. When you try to open the meeting app URL without the meeting ID e.g `https://abcdefghij.execute-api.us-east-1.amazonaws.com/Prod/V2/random` you will see the same screen.

Feel free to re-open the issue @mrgrue if it still persists.

**Comment by anuranduttaroy** [comment]
@davidilieberman this post (https://askubuntu.com/questions/1005623/libdbusmenu-glib-warning-unable-to-get-session-bus-failed-to-execute-child) seems to be similar to the error in the log you shared. 

Try adding `dbus-x11` at the end of this line https://github.com/aws-samples/amazon-chime-sdk-recording-demo/blob/master/Dockerfile#L13 and see if that helps. It should look something like this.

```
/usr/bin/apt-get install -y nodejs pulseaudio xvfb firefox ffmpeg xdotool unzip dbus-x11
```
