### ISSUE TITLE
Stack Formation error

### ISSUE THREAD

**Issue by rohit0337** [aws-samples/amazon-chime-sdk-recording-demo#28]
hello

while i am using deploy command from aws cli  my stack formation is showing me error and i am not able to get api for video recording

**Comment by aburnson** [comment]
@rohit0337, could you provide a little bit more information on what you tried and what error you are receiving?

**Comment by rohit0337** [comment]
hello

node ./deploy.js -b <my-bucket> -s <my-stack> -i <my-docker-image-uri> -r <region>
while i am running this command on my cloud formation i am getting this error 
 on cli i get this error:
Command sam failed with exit code 1 signal null
Error: Failed to create/update the stack: record-stack, Waiter StackCreateComplete failed: Waiter encountered a terminal failure state
 and cloud formation stack events are like this:
1. The following resource(s) failed to create: [InternetGateway, RecordingArtifactsUploadBucket, RecordingDemoBuildDeployGroup, VPC, EC2Role, CloudwatchLogsGroup, ECSCluster, RecordingDemoLambdaExecutionRole]. . Rollback requested by user.

2. Bucket name should be between 3 and 63 characters long

**Comment by anuranduttaroy** [comment]
Seems like the s3 bucket name is longer than 63 characters. This pull request https://github.com/aws-samples/amazon-chime-sdk-recording-demo/pull/24 should have fixed the long bucket name issue. 

Can you log into the [cloudformation console](https://console.aws.amazon.com/cloudformation/home) and search for your stack name and post the exact error messages you see there and for which resources.

**Comment by rohit0337** [comment]
the bucket name i am using its not long or short
and the issue from my cloudformation stack i already uploade on the previous comment
please check and help

**Comment by anuranduttaroy** [comment]
You said `Bucket name should be between 3 and 63 characters long`. 

If it's the [RecordingArtifactsUploadBucket](https://github.com/aws-samples/amazon-chime-sdk-recording-demo/blob/master/templates/RecordingDemoCloudformationTemplate.yaml#L74), we use the naming pattern `chime-meeting-sdk-<aws-account-id>-<region>-recordings`. With the PR https://github.com/aws-samples/amazon-chime-sdk-recording-demo/pull/24, we renamed it so that it does not exceed 64 characters. 

Can you confirm for which S3 bucket is cloudformation giving out that error? You can find that information in the Cloudformation console.

The other error `The following resource(s) failed to create: [InternetGateway, RecordingArtifactsUploadBucket, RecordingDemoBuildDeployGroup, VPC, EC2Role, CloudwatchLogsGroup, ECSCluster, RecordingDemoLambdaExecutionRole]. . Rollback requested by user.` is just because the rollback was initiated due to the s3 bucket creation failure.

**Comment by Anvit26** [comment]
You might have same cloud formation stack with the same name which is throwing error.

**Comment by anuranduttaroy** [comment]
No recent response. Closing this issue. Feel free to re-open if it's still not working for you @rohit0337
