### ISSUE TITLE
stack formation Creating multiple instance for video recording but not terminating after stop video recording

### ISSUE THREAD

**Issue by rohit0337** [aws-samples/amazon-chime-sdk-recording-demo#31]
hello
i use chime sdk java script and build an solution, for video recording now i am using your chime video recording sdk and passing my server's meeting url. whenever i start a video recording its create a instance due to auto scaling, if at a time there is two meetings going on there is two ec2 instance. but after stopping video recording instance is there autoscaling not terminating it or stopping it.

**Comment by anuranduttaroy** [comment]
Hey @rohit0337, you might be seeing 2 instances in your ASG because the desired capacity is set to 2 here in the cloudformation script: https://github.com/aws-samples/amazon-chime-sdk-recording-demo/blob/master/templates/RecordingDemoCloudformationTemplate.yaml#L38-L40. You can try changing this [configuration of the Autoscaling group](https://github.com/aws-samples/amazon-chime-sdk-recording-demo/blob/master/templates/RecordingDemoCloudformationTemplate.yaml#L276-L291) as per your needs to see if what works best for you. 

Also, one thing to note, we are using [Amazon ECS's managed scaling feature](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/asg-capacity-providers.html#asg-capacity-providers-managed-scaling) in our [demo](https://github.com/aws-samples/amazon-chime-sdk-recording-demo/blob/master/deploy.js#L170-L175). As per Amazon ECS documentation, it says *When **managed scaling** is enabled, Amazon ECS manages the scale-in and scale-out actions of the Auto Scaling group through the use of AWS Auto Scaling scaling plans. When managed scaling is disabled, you manage your Auto Scaling groups yourself.*

We are using the [Autoscaling group](https://github.com/aws-samples/amazon-chime-sdk-recording-demo/blob/master/templates/RecordingDemoCloudformationTemplate.yaml#L276-L291) created from the cloudformation script while deployment for creating a capacity provider in ECS and assigning that to the ECS Cluster here: https://github.com/aws-samples/amazon-chime-sdk-recording-demo/blob/master/deploy.js#L167-L187. 

Read more about about this here
- [Auto Scaling group capacity providers](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/asg-capacity-providers.html)
- [Amazon ECS managed scaling](https://docs.aws.amazon.com/AmazonECS/latest/APIReference/API_ManagedScaling.html)

Let me know if that helps. Feel free to re-open this issue if it still persists.
