### ISSUE TITLE
one instance only able to record one meeting

### ISSUE THREAD

**Issue by rohit0337** [aws-samples/amazon-chime-sdk-recording-demo#32]
hello 
i use chime sdk java script and build an solution, for video recording now i am using your chime video recording sdk and passing my server's meeting url. whenever i start a video recording recording start but when i am recording more meeting than max ec2 instance limit for auto scaling . then its gives error 

 "tasks": [],
 "failures": [
  {
   "arn": "arn:aws:ecs:ap-southeast-1:131006341016:container-instance/3ac0eaba-341c-4f12-96da-27e38b8dee5d",
   "reason": "DistinctInstance placement constraint unsatisfied."
  }
 ]
is one instance able to record only one meeting at a time

**Comment by anuranduttaroy** [comment]
You are seeing this error because while calling [`ecs.runTaask()` API from the Lambda function](https://github.com/aws-samples/amazon-chime-sdk-recording-demo/blob/master/src/index.js#L112-L114), we set a placement constraint for running 1 recording in 1 instance. 

```
placementConstraints: [{
    type: "distinctInstance"
}],
```

If you want to run multiple recordings in a single instance, you can remove that `placementConstraints ` property from the [`ecsRunTaskParams`](https://github.com/aws-samples/amazon-chime-sdk-recording-demo/blob/master/src/index.js#L112-L114) and try running the app. 

You can read more about Amazon ECS task placement here
- https://docs.aws.amazon.com/AmazonECS/latest/developerguide/task-placement.html
- https://docs.aws.amazon.com/AmazonECS/latest/developerguide/task-placement-constraints.html

Feel free to re-open this issue if this does not work.
