### ISSUE TITLE
Possibility of running recording on Fargate

### ISSUE THREAD

**Issue by pranjal-goswami** [aws-samples/amazon-chime-sdk-recording-demo#44]
Is it possible to run the recording tasks on Fargate?
I tried doing that but couldn't because the docker run requires mounting of volume and Fargate at the moment does not allow that. 

Anybody found a way of doing that?

**Comment by Aeramor** [comment]
Yes, we did that as a test but ended up not using it as a solution since join time was too long. (~45 seconds)

**Comment by robertbarron** [comment]
Hey @Aeramor we switched to fargate in order to reduce loading times when we had more than 1 recording, but our startup time is about 90 seconds. How did you manage to reduce join time with ec2?

Thanks

**Comment by Aeramor** [comment]
We had to switch to EC2 and just have additional capacity on standby; was the only way to get it fast enough (we got it down to ~2 seconds).

**Comment by anuranduttaroy** [comment]
> Hey @Aeramor we switched to fargate in order to reduce loading times when we had more than 1 recording, but our startup time is about 90 seconds. How did you manage to reduce join time with ec2?
> 
> Thanks

Hey @robertbarron 

Here are some improvements that you can make to reduce the start latency.

1. There is a `ECS_IMAGE_PULL_BEHAVIOR` in [ecs-agent-config](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/ecs-agent-config.html) which you can use to cache the docker image. This reduces the time to pull the image from ECR and use it to spin up the ECS Task. But for using this, you might have to get rid of this [placement constraint](https://github.com/aws-samples/amazon-chime-sdk-recording-demo/blob/master/src/index.js#L113) to use distinct instances for placing your tasks. If you use a larger instance to run multiple recording tasks in the same instance, we have noticed the task startup time as quick as 2-3 seconds. Then some additional time is taken for the [Firefox](https://github.com/aws-samples/amazon-chime-sdk-recording-demo/blob/master/recording/run.sh#L58) to start up and initialize [`ffmpeg`](https://github.com/aws-samples/amazon-chime-sdk-recording-demo/blob/master/recording/record.js#L25). 

2. This would be a big change but one other improvement that you can do is to use [ECS Service](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/ecs_services.html) to have a bunch of tasks running and listening to a queue/source for incoming requests. So here, instead of calling [startRecording -> ECS RunTask API](https://github.com/aws-samples/amazon-chime-sdk-recording-demo/blob/master/src/index.js#L118) or [stopRecording -> ECS StopTask API](https://github.com/aws-samples/amazon-chime-sdk-recording-demo/blob/master/src/index.js#L140), you would already have a service with `n` number of tasks running (which would already have `Firefox` and `ffmpeg` and other dependencies installed and running) and it can start recording as soon as a request comes in (in the source).

Let me know if this helps.

**Comment by anuranduttaroy** [comment]
> Is it possible to run the recording tasks on Fargate?
> I tried doing that but couldn't because the docker run requires mounting of volume and Fargate at the moment does not allow that.
> 
> Anybody found a way of doing that?

Hey @pranjal-goswami,

Yes we can run the recording task in Fargate too but as @Aeramor & @robertbarron mentioned, it takes some time to start the task as in Fargate, it has to allocate an instance, pull the docker image, and then start the container. This takes anywhere upwards of 20-30 seconds. But you can again follow the same optimizations mentioned in the comment above https://github.com/aws-samples/amazon-chime-sdk-recording-demo/issues/44#issuecomment-827778809 with Fargate to reduce the startup time.

**Comment by anuranduttaroy** [comment]
@pranjal-goswami feel free to re open this issue if you still have questions.

**Comment by trrystdev** [comment]
> Yes, we did that as a test but ended up not using it as a solution since join time was too long. (~45 seconds)

@Aeramor I want to change the ECS task to run on Fargate, but don't know enough about Fargate how to do it as yet. Can you please share what you had done earlier?
