### ISSUE TITLE
how to know the S3  file Object URL

### ISSUE THREAD

**Issue by jamontesg** [aws-samples/amazon-chime-sdk-recording-demo#47]
It is possible that when the recording stops, it returns the id of the S3 object URL ?
Or pass it a name parameter, to be used as a name in the S3 object

Kind Regards

**Comment by ziyiz-amzn** [comment]
Yeah, you may add an additional parameter(S3 object name) of start/end recording APIs in APIGateway. Then handle the new parameter in lambda, pass it as an environment variable when create s3 object.

**Comment by anuranduttaroy** [comment]
@jamontesg 

Yes, the S3 file name can be passed as a parameter. I just explained that here in this comment https://github.com/aws-samples/amazon-chime-sdk-recording-demo/issues/53#issuecomment-718919314. You can also return that file name/location that you compose as part of the response here https://github.com/aws-samples/amazon-chime-sdk-recording-demo/blob/f40d3b84db9940bcf7af206b3a532b5e634788b8/src/index.js#L128

Currently in this demo, the stop recording just stops the ECS task which is recording the meeting. The S3 file name is used only during start recording and is continuously uploading the data captured from the stdout stream here https://github.com/aws-samples/amazon-chime-sdk-recording-demo/blob/f40d3b84db9940bcf7af206b3a532b5e634788b8/recording/record.js#L77
So in this demo, returning the recording file path would not be possible during stop unless we store it somewhere during the start of the meeting. 

One other thing you could do is, as mentioned in the comment https://github.com/aws-samples/amazon-chime-sdk-recording-demo/issues/53#issuecomment-718919314, instead of using timestamp for the filename which we are doing here https://github.com/aws-samples/amazon-chime-sdk-recording-demo/blob/f40d3b84db9940bcf7af206b3a532b5e634788b8/recording/record.js#L76 you can use something like the `meeting-id` for composing the recording file name (which is static) and you can just compose the file path again when the `stopRecording` function is called and return the file location as part of the response here https://github.com/aws-samples/amazon-chime-sdk-recording-demo/blob/f40d3b84db9940bcf7af206b3a532b5e634788b8/src/index.js#L151

**Comment by anuranduttaroy** [comment]
@jamontesg Feel free to re-open if it's still an issue.
