### ISSUE TITLE
Custom S3 File name

### ISSUE THREAD

**Issue by tumbelin** [aws-samples/amazon-chime-sdk-recording-demo#53]
Hi, I already deploy the cloud formation, everything works fine, however I would like to have control over the video name from the recording. 
I saw this old pull request  (https://github.com/aws-samples/amazon-chime-sdk-recording-demo/pull/42), I know I can edit the lambda function as the PR suggest, but, where can I find the record.js file to edit too? or do I have to deploy the cloud formation again with the record.js file edited? or is there another way to change the name?

**Comment by anuranduttaroy** [comment]
The [record.js](https://github.com/aws-samples/amazon-chime-sdk-recording-demo/blob/master/recording/record.js) file is part of the docker image that runs when we try to start the recording. (Ref: It's called from [run.sh](https://github.com/aws-samples/amazon-chime-sdk-recording-demo/blob/master/recording/run.sh#L69) script which is called inside the [Dockerfile](https://github.com/aws-samples/amazon-chime-sdk-recording-demo/blob/master/Dockerfile#L21))

If you want to have a control over the name of the recording file, here is something you can do.

**Option 1**: As you mentioned, you need to update the record.js file and re-deploy the application.

**Option 2**: Control the recording artifact from the lambda function (This would require a deploy as well for the first time, but after that, if you want to update it, it can be done from the Lambda console too.)

1. From the [index.js](https://github.com/aws-samples/amazon-chime-sdk-recording-demo/blob/master/src/index.js#L104-L105) (which is the Lambda code), instead of passing the bucket name, you can also pass the file name which we are computing [here](https://github.com/aws-samples/amazon-chime-sdk-recording-demo/blob/master/recording/record.js#L76). It will look something like this.
    ```
    {
          name: "RECORDING_ARTIFACTS_FILE_NAME",
          value: recordingArtifactsFileName
    }
    ```
2. You can capture the file name here in [run.sh](https://github.com/aws-samples/amazon-chime-sdk-recording-demo/blob/master/recording/run.sh#L14) 
    ```
    S3_FILE_NAME=${RECORDING_ARTIFACTS_FILE_NAME}
    ```
3. Pass the file name as a parameter to the [record.js](https://github.com/aws-samples/amazon-chime-sdk-recording-demo/blob/master/recording/run.sh#L69) function here. e.g
    ```
    exec node /recording/record.js ${S3_BUCKET_NAME} ${S3_FILE_NAME} ${SCREEN_WIDTH} ${SCREEN_HEIGHT}
    ```
4. Capture the file name here in [record.js](https://github.com/aws-samples/amazon-chime-sdk-recording-demo/blob/master/recording/record.js#L11). e.g `const FILE_NAME = args[1];`
5. Use the file name here in [record.js](https://github.com/aws-samples/amazon-chime-sdk-recording-demo/blob/master/recording/record.js#L77)

As I mentioned before, this approach would require a deployment for the first time. But after that, if you want to change the path or name of the file, you can just directly change the logic from the Lambda console and that should immediately come into effect for the subsequent recordings.

**Comment by anuranduttaroy** [comment]
Let me know if this helps. Feel free to re-open if you have further questions about it.
