### ISSUE TITLE
Error RESOURCE:CPU start record

### ISSUE THREAD

**Issue by anhnt1-hblab** [aws-samples/amazon-chime-sdk-recording-demo#61]
When i start recording, I got an error like below.
I don't know what error this is and how to fix it, can you help me?
@anuranduttaroy @ltrung 
{
    "tasks": [],
    "failures": [
        {
            "arn": "arn:aws:ecs:us-east-2:468629877310:container-instance/08289ec66add4f558e413fbf78d11ed6",
            "reason": "RESOURCE:CPU"
        }
    ]
}

**Comment by ziyiz-amzn** [comment]
It is because the CPU of ECS task is limited. You can either try to decrease the default [ECSTaskCpu](https://github.com/aws-samples/amazon-chime-sdk-recording-demo/blob/master/templates/RecordingDemoCloudformationTemplate.yaml#L7-L9) and [ECSContainerCpu](https://github.com/aws-samples/amazon-chime-sdk-recording-demo/blob/master/templates/RecordingDemoCloudformationTemplate.yaml#L16-L18), but it may affect the quality of recording. Or you can ensure the instances in the ECS cluster have the required CPU resources, it not, you can file AWS customer ticket to ask for capacity increase.

Hope it helps.

**Comment by anuranduttaroy** [comment]
Hey @anhnt1-hblab, feel free to re-open this if you are still facing this issue.
