### ISSUE TITLE
Help with multiple recordings at the same time

### ISSUE THREAD

**Issue by robertbarron** [aws-samples/amazon-chime-sdk-recording-demo#81]
Hello,

I've been testing your solution for the past month so it can be used in an invitation only production environment. At first we used it out of the box with given configuration. When we were testing it, we found that when we had more than 2 recordings at the same time, the next recording took more than 10 minutes to join, and the next one, almost 30.

I think is a configuration issue from my side but we want to be able to have 15 recording at the same time. With the current configuration the joining time for the bot is taking too long.

is there any configuration we could change in order to reduce joining time?

Any help would be appreciated.

Thank you

**Comment by anuranduttaroy** [comment]
Hey @robertbarron 

There are some improvements that you could do reduce the bot join time. The 2nd point in the [FAQ](https://github.com/aws-samples/amazon-chime-sdk-recording-demo#faq) talks about it. 

For running multiple recordings, you can use the existing demo to start multiple meeting recordings, and by multiple, I mean multiple recordings of the same meeting and also different meetings. All you need to do is pass the Meeting URL of the meeting you want to record. In the default setup, we have used [Distinct Instance](https://github.com/aws-samples/amazon-chime-sdk-recording-demo/blob/master/src/index.js#L113) as the placement strategy. This ensures, the recording is started in a new instance in order to reduce the impact of failure. You can also use a different placement strategy or constraint which suits your needs. Here are some helpful links related to that.
1. [Amazon ECS task placement constraints](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/task-placement-constraints.html)
2. [Amazon ECS task placement strategies](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/task-placement-strategies.html)

For example, for running multiple recordings in the same EC2 instance, you can use the `binpack` placement strategy with `CPU` or `memory` as the field.

```
"placementStrategy": [
    {
        "field": "memory",
        "type": "binpack"
    }
]
```

Doing this would make sure, the current instance is fully utilized based on `memory` or `CPU` which ever you choose. Doing this would also speed up the bot join time as we have used [`ECS_IMAGE_PULL_BEHAVIOR ` as `prefer-cached`](https://github.com/aws-samples/amazon-chime-sdk-recording-demo/blob/be6e75b6a6397cfc485dfd45f6ca0842f5ac4421/templates/RecordingDemoCloudformationTemplate.yaml#L304) in our template, (Read more: [Amazon ECS Container Agent Configuration](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/ecs-agent-config.html)), which will make sure that the cached image is used and in-turn speed up the application launch time.

Let me know if this helps.

**Comment by shaheryar0129** [comment]
@anuranduttaroy I have quick questions...
1. when using **binpack** as our placement strategy,if the current instance is fully utilized and dont have enough resources to entertain new meetings,would it simply terminate the new meetings or it will created another instance to entertain new meetings?
2. Does it require deployment again?or I can just change it in our forked repo?

**Comment by shaheryar0129** [comment]
@anuranduttaroy ?

**Comment by anuranduttaroy** [comment]
> @anuranduttaroy I have quick questions...
> 
> 1. when using **binpack** as our placement strategy,if the current instance is fully utilized and dont have enough resources to entertain new meetings,would it simply terminate the new meetings or it will created another instance to entertain new meetings?
> 2. Does it require deployment again?or I can just change it in our forked repo?
> 3. Can I simply replace **placementConstraint** with **placementStrategy** with:
>    `"placementStrategy": [ { "field": "CPU", "type": "binpack" } ]`

1. No it won't terminate existing meetings. It would throw an error when you try to start a new meeting recording. The same error you mentioned here reason: https://github.com/aws-samples/amazon-chime-sdk-recording-demo/issues/91#issue-893640129 `'RESOURCE:CPU'`. If you have your autoscaling policy set, it will try to add more instances to accommodate  new meeting recording tasks.
2. If you are changing the placement strategy or constraint, then yes, that would require a deployment as it's part of the lambda code which needs to be updated in order to use the new constraint/strategy. In the current sample, it's here https://github.com/aws-samples/amazon-chime-sdk-recording-demo/blob/be6e75b6a6397cfc485dfd45f6ca0842f5ac4421/src/index.js#L112
3. Yes, you can replace `placementConstraint` with `placementStrategy`. It's part of the ECS RunTask request about which you can read more here: https://docs.aws.amazon.com/AmazonECS/latest/APIReference/API_RunTask.html#ECS-RunTask-request-placementStrategy

**Comment by anuranduttaroy** [comment]
Hey @robertbarron feel free to re-open this issue if you still have questions about multiple meeting recordings. @shaheryar0129 please open a new issue if you have more questions about your setup.
