### ISSUE TITLE
Enable CORS

### ISSUE THREAD

**Issue by cmdavinder** [aws-samples/amazon-chime-sdk-recording-demo#9]
API created from provided template - /recording doesn't allow CORS. Since the use case is to enable recording from user browser, it would be great to enable CORS as a part of API setup.

**Comment by aburnson** [comment]
While CORS could be enabled for the `/recording` endpoint, normally this endpoint would be called from the server application rather than directly from a client. The client application should make a request to the server application to begin recording (server can then verify if the client is authorized to do that) and the server application would then make the call to `POST /recording` on the recording infrastructure. That request (server-to-server) would not require CORS.

Going to close as I believe this to be out of the scope of the current demo since whether or not you would use CORS depends on how you integrate the recording infrastructure into your application.

**Comment by ttlpta** [comment]
@cmdavinder How you resolved this issue? I call API recording from my own server which is not in AWS and it has been blocked by CORS
